@echo off  
echo Starting QQ...  
start "" "C:\Program Files (x86)\Tencent\TIM\Bin\QQScLauncher.exe"
echo Starting Foxmail...  
start "" "D:\Program Files\Foxmail 7.2\Foxmail.exe"
echo Starting ²¼¹ÈÄñ...  
start "" "D:\Program Files (x86)\SisenStudio\SisenMESS-Client\SisenMESS.exe"
echo Starting 360...  
start "" "D:\Program Files (x86)\360\360Chrome\Chrome\Application\360chrome.exe"
echo Starting ¶¤¶¤...  
start "" "D:\Program Files (x86)\DingDing\main\current\DingTalk.exe"
echo Starting Î¢ÐÅ...  
start "" "D:\Program Files (x86)\Tencent\WeChat\WeChat.exe"